### ISSUE TITLE
Nanite Ore Detector/Mining Nanites Destroy server Simspeed

### ISSUE THREAD

**Issue by ryan3196** [nukeguard/NaniteConstructionSystem#103]
Feel free to delete this. Not 100% familiar with GitHub just yet. My issue -seems- to be resolved. I'll get back to you if i can replicate it.

**Comment by royco28** [comment]
i have the same server simspeed is jumping every 30 sec result in stuttering.

**Comment by SplenectomY** [comment]
Are you using the nanite mining? It's a common issue in non-dedicated servers. Change the settings file! The last few options are about the intensity and speed of voxel scanning and will improve your performance. If you're not mining, reduce the block scan rate.
