### ISSUE TITLE
Increase PCU to 5000 or more

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#14]
Current PCU is 1 and a nanite factory need a lot of computing resources, so i would recommend to set it to 5000 or maybe 7500.
e.g. a large rocket launcher have a PCU of 825

**Comment by nukeguard** [comment]
should each nanite require a PCU?
they aren't in world al the time

**Comment by nukeguard** [comment]
PCU limits are set, will show in next workshop update
