### ISSUE TITLE
Projections build with factory are owned by nobody and not count in pcu

### ISSUE THREAD

**Issue by zMOFOz** [nukeguard/NaniteConstructionSystem#23]
When using  a projector the blocks are not built by anyone and will not count in pcu

**Comment by zMOFOz** [comment]
or the owner of the Nanite block

**Comment by zMOFOz** [comment]
This is on dedicated server

**Comment by zMOFOz** [comment]
https://drive.google.com/file/d/1qq-DMjNYrVnFdJ1RdqDKmGxQ5S-ID4mc/view?usp=sharing

**Comment by Fank** [comment]
xml information in #32

**Comment by zMOFOz** [comment]
When built with a projector - builtby is not set

I have taken 2 blocks and did a compare for you
https://drive.google.com/open?id=1X8eMlwYDNloyPCx2kY_3MqVi4tfOR6a4

Steps: Porject a ship and build it
now go up to the ship and notice that built by: is missing on the blocks

this bug will cause any player in a faction to start attacking each ship as its built by (nobody)

**Comment by nukeguard** [comment]
Another reason why I think keen should set turrets to default off on Nobody targets

**Comment by Fank** [comment]
#45 should fix this, which will be published next monday by @nukeguard
