### ISSUE TITLE
Neighborhood bonus/sharing for factories

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#26]
Like factorio's nuclear reactor: 
- https://wiki.factorio.com/Nuclear_reactor#Neighbour_bonus
- https://www.reddit.com/r/factorio/comments/8xtt9m/some_helpful_data_for_people_looking_to_decide/

It's like placing a factory next to another factory, will get enabling the factory to get access to the other factories upgrades. But on the other side you will loose the 4 upgrades which can be places between the factories.

**Comment by nukeguard** [comment]
I like this idea, would this split the upgrade between them or double it?

**Comment by Fank** [comment]
[A][B]
[C][D]

Factory A can access upgrades from B & C (100% bonus), but not D because its not a directly connected factory.
Factory D can access upgrades from B & C (100% bonus), but not A because its not a directly connected factory.

So for this, it will double it.

**Comment by Jagernaut** [comment]
So if all slots are full of Construktion modules, each facility can access 12 Modules?

**Comment by Fank** [comment]
In my exampel above, yes

**Comment by SplenectomY** [comment]
Implemented with the introduction of the master-slave system. Friendly factories within range of each other or on the same grid system will now share upgrades as well as base statistics.
