### ISSUE TITLE
New power system

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#27]
Is i found here https://steamcommunity.com/sharedfiles/filedetails/?id=1270595120&searchtext=nanite

> I thought the nanite factory used way too much power
so i created this spinoff
(all credit goes to the original creator) (Nanite Factory Official Upload on workshop)
Changes:
Power reduction upgrades are 5x more effective

Maybe pushing the power reduction module, same as he did. Or connect the power to speed, so more power means faster nanites.

**Comment by Fank** [comment]
That makes sence, but we should decrease the default distance to 50meter or 100 instead of 300, and add the option to add more upgrades.

**Comment by nukeguard** [comment]
originally power was meant to be costly, due to the nanites just flying around and doing stuff for you, a distance module would be handy. With that module would be logical to have a default no upgrade factory use 1/4 of the power required if they can only go 50m. IMO distance module should increase distance by 50m each, and increase power use by 10mw each, so starting cost with no upgrades could be say 30-50mw, which would require at least 2-5 small reactors to function.

**Comment by nukeguard** [comment]
though i think 0.25 of current power is 25mw

**Comment by skyraze** [comment]
i feel like it should be more exponential, with each upgrade doubling the last. 
so 1 upgrade=+50 2=+150 3=350
with a max distance of 500.

**Comment by Fank** [comment]
50 meters each, 2x50 != 150. Or am i wrong?

**Comment by Fank** [comment]
And how many MW will this consume?

**Comment by skyraze** [comment]
each upgrade increases each stream by 1 MW, but that is to be determined after how much power should be used for default settings.

**Comment by nukeguard** [comment]
I like Skyraze breakdown of distance increases, 1mw per stream i think is reasonable.
a good start basic power cost I think should be 50mw thats only 3 small reactors
yes make the mining upgrade required for mining nanites to be functional

**Comment by Fank** [comment]
I think, a single factory without modules should use 1 small reactor. But the power usage increase expotantial with the modules, which can be used.
Like the balancing in the shield mod, want it faster and more parallel? Feed it with power!

**Comment by skyraze** [comment]
Hence why I think we should keep power controlled by streams. Since you
could have 4 streams and use only 10 mw, or have 80 streams and use 200 mw.

**Comment by nukeguard** [comment]
yea I guess a single small reactor could run base, and every upgrade increases power use, and if you have all upgrade slots filled it makes 80 streams and 200mw

**Comment by Jagernaut** [comment]
I think, Power should be consumed, while nanites are moving, not per update.
And the consumption should rise exponential by longer travelingdistances. ( Nanites are moved by the EM-Field of their facility )
Range-upgrades are a good idea to increase the maxium dimentions of the "work-space".
But the powercalculation should only be affected by the count, Job and traveldistance, of the nanites.
The upgrades should increase capabilities. And the power-upgrade reduce powercondumption.
For example:
Consumption in MW=
[1MW x Streamcount x Jobfactor x 1.1^(Travelingdistance/10)] x [0.9^(Powermodulcount)]

 4 Streams, Jobf.=1, Distance=10m, 0 Powermodules --> 4.4MW
20 Streams, Jobf.=1, Distance=10m, 0 Powermodules --> 22MW
80 Streams, Jobf.=1, Distance=10m, 0 Powermodules --> 88MW
 4 Streams, Jobf.=1, Distance=150m, 0 Powermodules --> 16MW
20 Streams, Jobf.=1, Distance=150m, 0 Powermodules --> 83MW
80 Streams, Jobf.=1, Distance=150m, 0 Powermodules --> 334MW
 4 Streams, Jobf.=1, Distance=300m, 0 Powermodules --> 70MW
20 Streams, Jobf.=1, Distance=300m, 0 Powermodules --> 349MW
80 Streams, Jobf.=1, Distance=300m, 0 Powermodules --> 1396MW

80 Streams, Jobf.=1, Distance=300m, 4 Powermodules --> 915MW

This makes it attractive to not build too far away and balance the whole thing dynamicly.
You can also balance the different Jobs individualy by adjusting the Jobfactor.
By setting this to 2 for mining, you double energyconsumption for all miningtasks.

Maybe a factor more for the weight, that the nanites are carrying, to balance that too. :-)

**Comment by Fank** [comment]
The power requirement is too high, 80 streams with 200mw is a good point, 80 streams with nearly 1.4GW is way too much.

**Comment by skyraze** [comment]
the point of the distance upgrade is to increase power capacity of the nanites to allow farther ranges, hence increases wattage per stream.
if one stream uses 2 mw, 4 streams would be 8 mw. add 3 upgrade modules, thats 5 mw each now its 20 mw. however if you take into account something like my miner, it uses a total of 80 streams for mining. if it had 3 distance upgrades, that is 5 mw per stream that would be 400mw of power, i'd say 400 mw for 4 nanite factorys with max distance is pretty good, as with a small ship factory being 8mw i think that's good too.

**Comment by SplenectomY** [comment]
New power system is in for factory and ore detector. Tested, works great. Only consumes power while in "Active state" (when it's throwing out nanites). Power usage reduction upgrade modules are functional. Looking good.
