### ISSUE TITLE
Possibility of mining hammer not detecting ore deeper than a few meters

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#3]
Users have reported mining hammer either not detecting ore, not functioning, or animation breaking. Mining works locally for me, only issue I saw was that hammer stopped working sometimes on reload.

**Comment by WufPufScarabee** [comment]
i heve the issue with texture and not functioning. Not even the light blinks.
![schermopname 202](https://user-images.githubusercontent.com/36576819/36346109-380c4874-1438-11e8-8691-5101816cdbf4.png)

**Comment by JustCallMeAce** [comment]
Having an issue where I place the hammer on Earth(only way Ive tested) with ore 50m away and it not mining anything. Textures and animations for the hammer work but no luck mining anything

**Comment by JustCallMeAce** [comment]
Update: After hours of messing with it, it started mining when the NUHOL got within 30m and the NCF within 300m of NUHOL. Maybe the range just needs to be buffed.

**Comment by nukeguard** [comment]
I have updated the range, need to upload to workshop. I have it mining ore from <100m now. I won't be able to upload till thursday

**Comment by nukeguard** [comment]
Not yet

**Comment by Fank** [comment]
Same problem as #22 should be fixed with 2.0
