### ISSUE TITLE
New nanite factory type welder, ship_tool can dmg player

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#35]
New block type of welder for factory, can use ship_tool empty in welder to cause damage to player instead of scripting damage area in. Will need to toggle dmg on/off with script while block is still on, unless we want to leave damage enabled all the time while on and not just when active.

**Comment by Fank** [comment]
Is this something in the model definition? Or how can this be done?

**Comment by nukeguard** [comment]
I'll have to add the empty in the model, it is labeled dummy_detector_ship_tool_1

**Comment by nukeguard** [comment]
can size the empty to the space that it should affect

**Comment by Fank** [comment]
Nice it think it's linked to the "IsWorking" property, in IMyShipWelder. So i should be able to control it.

**Comment by nukeguard** [comment]
model conversion complete and empty in place cubeblock.sbc is set for welder definition 
    <Definition xsi:type="MyObjectBuilder_ShipWelderDefinition">
      <Id>
        <TypeId>ShipWelder</TypeId>

**Comment by SplenectomY** [comment]
The definition seems fine, however in its current state, it should be dealing damage while it's "On" just like a ship welder does, but it is not. I can't tell what's missing.

**Comment by nukeguard** [comment]
corrected mistyped empty name in model, and changed AoE size to be within refractors. Now causes damage to player when on.

**Comment by SplenectomY** [comment]
This definitely works now, but I have no idea how we will get this to toggle without doing some digging. MyCubeBlock.IsWorking has a private "set" property and I don't see any methods that toggle IsWorking specifically, unless you know something I don't, @Fank .  However, I believe MyShipWelder counts as a IMyGunObject and we might be able to toggle it with BeginShoot()/EndShoot() or something.

For now I'm going to close this. Getting the damage to only trigger in the "Active" state can be a separate issue for 2.1.

**Comment by nukeguard** [comment]
you may be able to scale the area of effect size because these parameters are in the sbc definition. 

`
      <SensorRadius>4</SensorRadius>
      <SensorOffset>0</SensorOffset>`

**Comment by nukeguard** [comment]
if you set sensor radius to 0 it shouldn't damage player unless they are directly on the empty location.

**Comment by SplenectomY** [comment]
I'll test that and see if it works.
