### ISSUE TITLE
Texture to separate old from new models

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#42]
In v2 the factory were renamed to facility, so we need to change the texture of the old factory.
So people can easier identify there is a old one and replace it.
Rusty texture?

**Comment by skyraze** [comment]
i would make them spark and make weird sounds. maybe even make their power requirements something stupid like 500 MW, like its shorting out. that way people will either have to remove them or replace them ASAP.

**Comment by Fank** [comment]
I like the spark idea, but it should do nothing, so no power.

**Comment by nukeguard** [comment]
finished, nanite factory and old mining hammer now have rusty models, all upgrade models still will be functional with working block.
