### ISSUE TITLE
Nanite block icons does not match the one space engineers have

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#46]
They should be lightblue to white no other colors.

![image](https://user-images.githubusercontent.com/1900106/43980867-01a424b4-9cf0-11e8-9745-3fdd4cb26468.png)

Icon from control facility is low quality.

**Comment by nukeguard** [comment]
sometimes wish their icons were colored, especially the ore, ingot, and tool icons. But I can set these to blueish white.

**Comment by Fank** [comment]
It should all the same, color or blueish white. But not mixing them.

**Comment by nukeguard** [comment]
Checking this, think I have fixed this issue.

**Comment by SplenectomY** [comment]
Colors are fixed, but some blocks are not in the nanite category. New upgrades, new ore detector and the beacons.
![image](https://user-images.githubusercontent.com/4369778/47881480-9e2c4a80-ddfc-11e8-9ef0-4ed8e241918a.png)

**Comment by nukeguard** [comment]
i'll get those added to block categories

**Comment by SplenectomY** [comment]
The only thing we need now for the GUI to be completely done for V2 is an icon for the mining rig.

**Comment by nukeguard** [comment]
oh the big mining rig, yes I'll get that done when model is finalized. Will also need icons for the 5 attachment parts

**Comment by SplenectomY** [comment]
Ah forgot to mention, a few upgrade modules just use the generic construction upgrade model as well. I can find out which ones, but I'm sure they're listed in the cubeblocks file anyway.

**Comment by nukeguard** [comment]
They are listed, I haven't finished the models for them yet

**Comment by SplenectomY** [comment]
This appears to be all done and ready for V2. We will open separate issues for future problems that might come up.
