### ISSUE TITLE
Configurable amount of nanites

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#56]
a request for "on your nanite factory can you also put a config for the amount of nanites" by Dirty_Nightmare

**Comment by skyraze** [comment]
Isn't that already possible?

**Comment by Fank** [comment]
It should be

**Comment by SplenectomY** [comment]
The box is there, but it doesn't change anything currently if you modify the value. I found some old code in there, though, that seems to limit the nanites based off the name:
`if (!block.CustomName.ToLower().Contains("MaxNanites".ToLower()))
                    return;

                Regex regexObj = new Regex(@".*?MaxNanites[ :](\d{1,4})", RegexOptions.Singleline | RegexOptions.IgnoreCase);
                Match matchResults = regexObj.Match(block.CustomName);
                int value = 0;

                if (matchResults.Success && int.TryParse(matchResults.Groups[1].Value, out value))
                    m_userDefinedNaniteLimit = value;`

I'm going to change this to actually use the text field that's in the block controls.
