### ISSUE TITLE
Change nanite target system to grid based instead of block based

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#57]
Currently the nanite target will be checked per block.
For some target like construction, projection and maybe other, the check mechanic should be changed to grid, so that the grid will make this check and all control facilites on the grid will do the job.
This should help to decrease the server load.
Because today we noticed that running 8 control facilites on a grid, while multiple people were constructing and deconstruction. The total cpu host load is very high, and with this system the load should be lowered a lot.

**Comment by skyraze** [comment]
"8" you have a lot of facilities don't you. ;)

**Comment by Fank** [comment]
These are 16 now :), but the load increase each time i placed one more, so i think this is a good idea.
Than the load will only increase at a very small amount by control facilites on grid.

**Comment by SplenectomY** [comment]
The master-slave system I have implemented now virtually eliminates duplicate scanning of grids in most scenarios.
