### ISSUE TITLE
Pink control factory

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#58]
![image](https://user-images.githubusercontent.com/1900106/44755197-7501ec00-ab25-11e8-9b20-dd8095dc9403.png)

I saw it by using the admin view, and select a grid, it loaded and i saw that pink think.
I also found this one which is related https://steamcommunity.com/workshop/filedetails/discussion/219757726/1760230157501825315/

Saw this issue for the first time, it does not care about lod or something. Its just pink.
Will take a look at it tomorrow, maybe find a reproduceable example.

**Comment by Fank** [comment]
![image](https://user-images.githubusercontent.com/1900106/44807936-2444ce80-abcb-11e8-9d3a-5e02f36606d4.png)

**Comment by Fank** [comment]
![image](https://user-images.githubusercontent.com/1900106/44875513-b538aa00-ac9e-11e8-9f12-a7e9cb87432b.png)

**Comment by nukeguard** [comment]
All purple is fixed now

**Comment by nukeguard** [comment]
blah, I missed one

**Comment by nukeguard** [comment]
this should all be fixed now

**Comment by Fank** [comment]
don't worry i'll find it all

**Comment by Fank** [comment]
Then close it
