### ISSUE TITLE
Huge performance issues on larger grids

### ISSUE THREAD

**Issue by Fank** [nukeguard/NaniteConstructionSystem#6]
I build https://steamcommunity.com/sharedfiles/filedetails/?id=695986783 starting in the front with a nanite system and later one in the center of the ship.
After about 3/4 projection completion, we started noticing sim speed drops, and they get heavier foreach block placed by projection nanites.
The drops increases with the amount of players which are connected.
- 1 player 0.9 speed
- 2 players 0.7 speed
- 3 players 0.5 speed
- 5 players 0.2 speed

The drop duration is about 500ms, but appear more often.

I noticed that changing the nanite system to following:
- front: construct/repair only
- center: projection only

Does not change anything, it looks like it will always check if there a possible targets for X, whether the options i checked or not.
Could we change the system that it will only check stuff, when its checked?
Or maybe a option for manual block check, or custom check interval ingame?

Because the grid above is:
1. long (450 meters)
2. contains lots of blocks (nearly 100k)

Maybe #5 could improve performance.

I finished building it, but its crap so i need to deconstruct them again, will test deconstruction on the ship soon :D

**Comment by nukeguard** [comment]
I would definitely need help with anything like that, I don't know C# well enough to add things.

**Comment by Fank** [comment]
I could try to fix this, i only need to know which behaviour is wanted.

**Comment by nukeguard** [comment]
I would say second option would be best

**Comment by Fank** [comment]
I did some research and found out that:
- every 5 sec the server sim drops -> https://github.com/nukeguard/NaniteConstructionSystem/blob/09628bef44eafd4f00337a6a65f826efb66e7224/Entities/NaniteConstructionBlock.cs#L503
- And every 2 sec the client sim speed drops (i think its the time between spinning up, error out of range, spinning down, but not sure)

**Comment by Fank** [comment]
Ill try to find the performance issues, when i have got mods to work locally.

**Comment by Fank** [comment]
This works for now, but should still be worked on in the future
