### ISSUE TITLE
Conveyor's Not connecting

### ISSUE THREAD

**Issue by WestcoastBigs** [nukeguard/NaniteConstructionSystem#64]
I just recently downloaded the mod and when i launched it in my world everything worked normally however conveyors wouldn't connect to it at all. I tried all different combinations and even launched a new world with just this mod and still the conveyors wouldn't register a connection.

**Comment by WestcoastBigs** [comment]
Nevermind, i was able to fix the issue by actually hooking up an oxygen system in my base.

**Comment by nukeguard** [comment]
that is strange that hooking an oxygen system to the base made it work...
