### ISSUE TITLE
Factory center orb is MIA, with update 1.188

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#65]
![image](https://user-images.githubusercontent.com/30876973/47384651-dda8b780-d6d5-11e8-986b-778246a7b9c5.png)

**Comment by nukeguard** [comment]
I don't see why it's not showing up, i don't see any errors, or see anything in the SE.log

**Comment by nukeguard** [comment]
I could change how this center model is attached, I can add a subpart to the block and attach it that way then you guys will just have to use TryGetSubpart method and translate/rotate the subpart

**Comment by SplenectomY** [comment]
Let me know when you've attached it and I'll finish it in the code

**Comment by nukeguard** [comment]
center object is attached now via subpart named subpart_sphere, it shows up in the base now.

**Comment by SplenectomY** [comment]
Allright. I'll tie it in with the spooling and get it up and running, probably Monday. Just have to familiarize myself with subpart movement.
