### ISSUE TITLE
InitializeControls() is called twice, resulting in duplicate terminal controls

### ISSUE THREAD

**Issue by SplenectomY** [nukeguard/NaniteConstructionSystem#68]
This function, which adds the custom checkboxes, fields and sliders to the block, is called in Core.cs and MessageHub.cs. I think @Fank rewrote some of the message/sync handling to make it better for clients, but this can be turned off at the very least for single player. However, I have a feeling this will also lead to duplicate controls for multiplayer. Once we get V2 on a server, I'm going to test this, confirm that it's a problem in both SP and MP and then deal with it.

**Comment by Fank** [comment]
I developed this system in mp only, and never saw it, so must be sp only.

**Comment by SplenectomY** [comment]
Ok. If that's the case, I'll just make the MessageHub not fire if it's not a multiplayer session, and that should fix it.

**Comment by SplenectomY** [comment]
My players confirmed that it's not an issue at all on the server, so I'll throw in a quick conditional for single player and we'll be good.
