### ISSUE TITLE
Nanite construction breaks programmable blocks

### ISSUE THREAD

**Issue by Baughn** [nukeguard/NaniteConstructionSystem#69]
Using the construction function, I get this warning in shift-f1:

```
Mod Nanite Control Facility - Automated Construction is invoking Programmable Blocks from parallel threads. This is not safe and might cause the game to crash or behave unexpectedly.
```

And, in fact, I've seen several DS crashes while using it for construction. What happens more often is that scripts stop running, with the script block showing a "Script too complex" error message. I've also observed stranger behaviour, where the script seemingly keeps running but starts behaving strangely.

In one instance, I had an inventory management script (Isy's) move -2147483647 (yes, -2^31) items into a cargo container. The game then crashed when I tried to move them.

All such behaviour ceases once I disable the NCF block.

**Comment by SplenectomY** [comment]
@Baughn fixed in V2. Soon (tm).
