### ISSUE TITLE
Issue with Nanite Control not working on dedicated server.

### ISSUE THREAD

**Issue by Restiphani** [nukeguard/NaniteConstructionSystem#77]
https://steamcommunity.com/workshop/filedetails/discussion/219757726/1733216261964398122/

Here are the log files I believe you requested
[Space Engineers Logs.zip](https://github.com/nukeguard/NaniteConstructionSystem/files/2602232/Space.Engineers.Logs.zip)

**Comment by SplenectomY** [comment]
This is for V1. I don't see anything in the logs that would show that the mod itself isn't working. What exact problem are you having?

**Comment by SplenectomY** [comment]
@Restiphani Ahhh. This is because the original Nanite Control Factory is based on type OxygenFarm. Nothing we can do about it. It's changed in V2. Be patient, or switch to the dev build here https://steamcommunity.com/sharedfiles/filedetails/?id=1485968462
